import { useEffect, useState } from "react";
import { Alert, Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag } from "antd";
import * as catalogApi from "@/api/catalog";
import type { SubjectMapping } from "@/api/types";
import { PageHeader, useConfirm, useToast } from "@/components";
import { MAPPING_STATUS_LABEL } from "@/utils/constants";

export default function AdminSubjects() {
  const toast = useToast(); const confirm = useConfirm(); const [rows, setRows] = useState<SubjectMapping[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [status, setStatus] = useState<string | undefined>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<SubjectMapping | null>(null); const [open, setOpen] = useState(false); const [form] = Form.useForm();
  async function load() { setLoading(true); setError(null); try { const result = await catalogApi.listMappings({ status, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("科目映射加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page, status]);
  function openCreate() { setEditing(null); form.resetFields(); form.setFieldsValue({ is_leaf: true, include_in_holdings: false, rule_version: "1" }); setOpen(true); }
  function openEdit(row: SubjectMapping) { setEditing(row); form.setFieldsValue({ subject_code_or_prefix: row.subject_code_or_prefix, raw_name_pattern: row.raw_name_pattern, standard_category: row.standard_category, is_leaf: row.is_leaf, include_in_holdings: row.include_in_holdings, rule_version: row.rule_version }); setOpen(true); }
  async function save() { try { const values = await form.validateFields() as catalogApi.SubjectMappingInput; if (editing) await catalogApi.updateMapping(editing.id, values); else await catalogApi.createMapping(values); toast.success("科目映射已保存"); setEditing(null); setOpen(false); await load(); } catch { setError("科目映射保存失败，请检查输入"); } }
  async function disable(row: SubjectMapping) { const reason = await confirm({ title: "停用科目映射", description: "停用只影响后续解析，不修改历史数据。", reasonRequired: true, danger: true, okText: "确认停用" }); if (reason === null) return; try { await catalogApi.disableMapping(row.id, reason); toast.success("科目映射已停用"); await load(); } catch { setError("科目映射停用失败"); } }
  return <div className="fd-page"><PageHeader title="科目与模板" desc="维护原始科目到标准资产、负债和持仓类别的映射" extra={<Button type="primary" onClick={openCreate}>新增映射</Button>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Space><Select allowClear placeholder="状态" value={status} onChange={(v) => { setPage(1); setStatus(v); }} options={Object.entries(MAPPING_STATUS_LABEL).map(([value, label]) => ({ value, label }))} /></Space><Table style={{ marginTop: 12 }} rowKey="id" size="small" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, showSizeChanger: false, onChange: setPage }} columns={[{ title: "代码/前缀", dataIndex: "subject_code_or_prefix" }, { title: "名称匹配", dataIndex: "raw_name_pattern" }, { title: "标准类别", dataIndex: "standard_category" }, { title: "叶子", dataIndex: "is_leaf", render: (v: boolean) => v ? "是" : "否" }, { title: "计入持仓", dataIndex: "include_in_holdings", render: (v: boolean) => v ? "是" : "否" }, { title: "规则版本", dataIndex: "rule_version" }, { title: "状态", dataIndex: "status", render: (v: SubjectMapping["status"]) => <Tag>{MAPPING_STATUS_LABEL[v]}</Tag> }, { title: "操作", render: (_: unknown, row: SubjectMapping) => <Space><Button type="link" size="small" onClick={() => openEdit(row)}>编辑</Button>{row.status === "active" && <Button type="link" danger size="small" onClick={() => void disable(row)}>停用</Button>}</Space> }]} /></Card><Modal open={open} title={editing ? "编辑科目映射" : "新增科目映射"} onCancel={() => { setOpen(false); setEditing(null); form.resetFields(); }} onOk={() => void save()} okText="保存"><Form form={form} layout="vertical"><Space wrap><Form.Item label="科目代码/前缀" name="subject_code_or_prefix"><Input /></Form.Item><Form.Item label="原始名称匹配" name="raw_name_pattern"><Input /></Form.Item></Space><Form.Item label="标准类别" name="standard_category" rules={[{ required: true }]}><Input /></Form.Item><Space><Form.Item label="是否叶子" name="is_leaf" valuePropName="checked"><Switch /></Form.Item><Form.Item label="计入持仓" name="include_in_holdings" valuePropName="checked"><Switch /></Form.Item></Space><Form.Item label="规则版本" name="rule_version" rules={[{ required: true }]}><Input /></Form.Item></Form></Modal></div>;
}
