import { useEffect, useState } from "react";
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tag } from "antd";
import * as riskApi from "@/api/risk";
import type { RiskRule } from "@/api/types";
import { PageHeader, useToast } from "@/components";
import { RISK_RULE_TYPES, RISK_SEVERITY_LABEL, type RiskSeverity } from "@/utils/constants";

const labels: Record<string, string> = { daily_return: "日收益下跌", max_drawdown: "最大回撤", current_drawdown: "当前回撤", single_position_weight: "单票权重", top_five_weight: "前五大权重", concentration: "集中度" };
export default function AdminRiskRules() {
  const toast = useToast(); const [rows, setRows] = useState<RiskRule[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [includeHistory, setIncludeHistory] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<RiskRule | null>(null); const [form] = Form.useForm();
  async function load() { setLoading(true); setError(null); try { const result = await riskApi.listRules({ include_history: includeHistory, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("风险规则加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page, includeHistory]);
  function openCreate() { setEditing(null); form.resetFields(); form.setFieldsValue({ scope: "all", severity: "warning", enabled: true }); setOpen(true); }
  function openEdit(row: RiskRule) { setEditing(row); form.setFieldsValue({ rule_code: row.rule_code, rule_type: row.rule_type, scope: row.scope, threshold: Number(row.threshold), severity: row.severity, enabled: row.enabled }); setOpen(true); }
  async function save() { try { const values = await form.validateFields(); if (editing) { const { rule_code: _ruleCode, ...changes } = values as riskApi.RiskRuleCreateInput; await riskApi.updateRule(editing.id, changes); } else { await riskApi.createRule(values as riskApi.RiskRuleCreateInput); } toast.success("风险规则已保存并生成版本"); setOpen(false); setEditing(null); await load(); } catch { setError("风险规则保存失败，请检查输入或版本冲突"); } }
  return <div className="fd-page"><PageHeader title="风险规则" desc="维护可由估值 Excel 数据计算的收益、回撤和集中度规则，修改自动生成新版本" extra={<Button type="primary" onClick={openCreate}>新建规则</Button>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Space><Switch checked={includeHistory} onChange={(v) => { setPage(1); setIncludeHistory(v); }} /><span>包含历史版本</span></Space><Table style={{ marginTop: 12 }} rowKey="id" size="small" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, showSizeChanger: false, onChange: setPage }} columns={[{ title: "规则编码", dataIndex: "rule_code" }, { title: "规则类型", dataIndex: "rule_type", render: (v: string) => labels[v] ?? v }, { title: "范围", dataIndex: "scope" }, { title: "阈值", dataIndex: "threshold" }, { title: "严重度", dataIndex: "severity", render: (v: RiskSeverity) => <Tag>{RISK_SEVERITY_LABEL[v]}</Tag> }, { title: "版本", dataIndex: "version", render: (v: string) => `v${v}` }, { title: "状态", dataIndex: "enabled", render: (v: boolean) => v ? "启用" : "停用" }, { title: "操作", render: (_: unknown, row: RiskRule) => <Button type="link" size="small" onClick={() => openEdit(row)}>生成新版本</Button> }]} /></Card><Modal open={open} title={editing ? "生成风险规则新版本" : "新建风险规则"} onCancel={() => setOpen(false)} onOk={() => void save()} okText="保存"><Form form={form} layout="vertical"><Form.Item label="规则编码" name="rule_code" rules={[{ required: true }]}><Input disabled={Boolean(editing)} /></Form.Item><Form.Item label="规则类型" name="rule_type" rules={[{ required: true }]}><Select options={RISK_RULE_TYPES.map((value) => ({ value, label: labels[value] }))} /></Form.Item><Form.Item label="适用范围" name="scope" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="阈值" name="threshold" rules={[{ required: true }]}><InputNumber style={{ width: "100%" }} /></Form.Item><Form.Item label="严重度" name="severity" rules={[{ required: true }]}><Select options={Object.entries(RISK_SEVERITY_LABEL).map(([value, label]) => ({ value, label }))} /></Form.Item><Form.Item label="启用" name="enabled" valuePropName="checked"><Switch /></Form.Item></Form></Modal></div>;
}
