import { useState } from "react";
import { Alert, Button, Card, Input, Modal, Space, Statistic, Typography } from "antd";
import * as systemApi from "@/api/system";
import type { MaintenanceResult } from "@/api/types";
import { PageHeader, useToast } from "@/components";

export default function AdminRetention() {
  const toast = useToast(); const [preview, setPreview] = useState<MaintenanceResult | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [executeOpen, setExecuteOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState("");
  async function runPreview() { setBusy(true); setError(null); try { setPreview((await systemApi.previewRetention()).data); toast.success("清理预演已完成"); } catch { setError("清理预演失败，请检查运维状态"); } finally { setBusy(false); } }
  async function execute() { if (confirmation !== "DELETE_EXPIRED_SOURCE_FILES" || !reason.trim()) return; setBusy(true); setError(null); try { setPreview((await systemApi.executeRetention(reason.trim())).data); setExecuteOpen(false); setConfirmation(""); setReason(""); toast.success("清理执行完成"); } catch { setError("清理执行失败，系统未绕过安全检查"); } finally { setBusy(false); } }
  const summary = preview?.summary ?? {};
  return <div className="fd-page"><PageHeader title="数据保留与备份" desc="管理员先预演，再按安全检查执行原始文件滚动清理" />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Space wrap><Button onClick={() => void runPreview()} loading={busy}>清理预演</Button><Button danger disabled={!preview || preview.status === "failed"} onClick={() => setExecuteOpen(true)}>确认执行</Button></Space><Typography.Paragraph style={{ marginTop: 16 }}>清理只作用于已过保留期且通过备份、任务引用、复核和审计锁检查的原始文件；数据库标准化数据和审计记录不会删除。</Typography.Paragraph>{preview && <Space wrap><Statistic title="候选文件" value={Number(summary.candidate_count ?? 0)} /><Statistic title="计划删除" value={Number(summary.planned_count ?? 0)} /><Statistic title="已删除" value={Number(summary.deleted_count ?? 0)} /><Statistic title="错误数" value={Number(summary.error_count ?? 0)} /></Space>}</Card><Modal open={executeOpen} title="确认执行原始文件清理" onCancel={() => setExecuteOpen(false)} onOk={() => void execute()} okText="确认执行" okButtonProps={{ danger: true, disabled: confirmation !== "DELETE_EXPIRED_SOURCE_FILES" || !reason.trim(), loading: busy }}><Typography.Paragraph>请输入固定确认短语，并填写本次操作原因。后端仍会执行全部安全检查。</Typography.Paragraph><Input placeholder="DELETE_EXPIRED_SOURCE_FILES" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /><Input.TextArea style={{ marginTop: 12 }} placeholder="操作原因" value={reason} onChange={(e) => setReason(e.target.value)} maxLength={1000} showCount /></Modal></div>;
}
