import { useEffect, useState } from "react";
import { Alert, Button, Card, Col, Row, Space, Table } from "antd";
import { useNavigate } from "react-router-dom";
import * as dashboardApi from "@/api/dashboard";
import { PageHeader, StatusRibbon, Num, QualityBadge, useToast } from "@/components";
import { dec, dateStr, pct, returnColor } from "@/utils/format";
import type { DashboardOverview } from "@/api/types";

export default function Dashboard() {
  const navigate = useNavigate(); const toast = useToast();
  const [overview, setOverview] = useState<DashboardOverview | null>(null); const [coverage, setCoverage] = useState({ available: 0, total: 0 });
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const result = await dashboardApi.getOverview(); setOverview(result.data); setCoverage(result.meta.coverage); } catch { setError("总览数据加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function exportOverview() { try { const r = await fetch("/api/v1/exports/overview", { credentials: "include" }); if (!r.ok) throw new Error(); const b = await r.blob(); const u = URL.createObjectURL(b); const a = document.createElement("a"); a.href = u; a.download = "company-overview.csv"; a.click(); URL.revokeObjectURL(u); toast.success("总览已导出"); } catch { toast.error("导出失败，请稍后重试"); } }
  return <div className="fd-page"><PageHeader title="公司总览" desc="查看已发布估值数据的规模、收益、风险和覆盖情况" extra={<Space><Button onClick={() => void load()} loading={loading}>刷新</Button><Button onClick={() => void exportOverview()}>导出总览</Button><Button onClick={() => navigate("/risk")}>风险事件</Button></Space>} />{error && <Alert type="error" showIcon message={error} style={{ marginBottom: 12 }} />}<StatusRibbon asOf={overview?.as_of ?? null} version={null} coverage={coverage} quality={overview?.quality_status ?? "pending"} /><Row gutter={[12, 12]} style={{ marginTop: 16 }}><Col xs={24} sm={12} lg={6}><Card className="fd-kpi"><div className="fd-kpi__label">总净资产</div><div className="fd-kpi__value">{dec(overview?.total_net_assets, 2)}</div><div className="fd-kpi__sub">{overview?.fund_count ?? 0} 只产品</div></Card></Col><Col xs={24} sm={12} lg={6}><Card className="fd-kpi"><div className="fd-kpi__label">公司日收益</div><div className="fd-kpi__value" style={{ color: returnColor(overview?.company_daily_return) }}>{pct(overview?.company_daily_return)}</div><div className="fd-kpi__sub">后端已计算结果</div></Card></Col><Col xs={24} sm={12} lg={6}><Card className="fd-kpi"><div className="fd-kpi__label">待处理风险事件</div><div className="fd-kpi__value">{overview?.risk_event_count ?? "—"}</div><div className="fd-kpi__sub">来自风险事件记录</div></Card></Col><Col xs={24} sm={12} lg={6}><Card className="fd-kpi"><div className="fd-kpi__label">数据覆盖率</div><div className="fd-kpi__value">{coverage.total ? `${Math.round(coverage.available / coverage.total * 100)}%` : "—"}</div><div className="fd-kpi__sub">已发布产品 / 活跃产品</div></Card></Col></Row><Card style={{ marginTop: 12 }} title={<span className="fd-section-title">产品运行概览</span>}><Table rowKey="id" size="small" loading={loading} dataSource={overview?.funds ?? []} pagination={false} columns={[{ title: "产品名称", dataIndex: "name", render: (value: string, row: DashboardOverview["funds"][number]) => <a onClick={() => navigate(`/funds/${row.id}`)}>{value}</a> }, { title: "估值日", dataIndex: "valuation_date", render: dateStr }, { title: "单位净值", dataIndex: "unit_nav", align: "right", render: (v: string | null) => <Num>{dec(v, 4)}</Num> }, { title: "日收益", dataIndex: "daily_return", align: "right", render: (v: string | null) => <Num style={{ color: returnColor(v) }}>{pct(v)}</Num> }, { title: "分析状态", dataIndex: "analysis_status" }, { title: "质量", render: () => <QualityBadge status={overview?.quality_status ?? "pending"} /> }]} /></Card></div>;
}
