import { useEffect, useState } from "react";
import { Alert, Button, Card, Input, Select, Space, Table, Tag } from "antd";
import { useNavigate } from "react-router-dom";
import * as fundsApi from "@/api/funds";
import * as downloads from "@/api/downloads";
import { PageHeader, Num, QualityBadge, useToast } from "@/components";
import { dateStr, dec, pct, returnColor } from "@/utils/format";
import type { FundListItem } from "@/api/types";

export default function Funds() {
  const navigate = useNavigate(); const toast = useToast(); const [rows, setRows] = useState<FundListItem[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [q, setQ] = useState(""); const [status, setStatus] = useState<string>(); const [asOf, setAsOf] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const result = await fundsApi.list({ q: q || undefined, status, as_of: asOf || undefined, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("产品列表加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page, q, status, asOf]);
  async function exportFunds() { try { await downloads.downloadBlob(`/exports/funds${asOf ? `?as_of=${encodeURIComponent(asOf)}` : ""}`, "funds.csv"); toast.success("产品列表已导出"); } catch { toast.error("导出失败，请稍后重试"); } }
  return <div className="fd-page"><PageHeader title="产品列表" desc="查看产品的已发布估值状态" extra={<Space><Button onClick={() => void load()} loading={loading}>刷新</Button><Button onClick={() => void exportFunds()}>导出产品列表</Button></Space>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Space wrap className="fd-filterbar"><Input.Search allowClear placeholder="产品名称" onSearch={(v) => { setPage(1); setQ(v); }} style={{ width: 200 }} /><Select allowClear placeholder="状态" value={status} onChange={(v) => { setPage(1); setStatus(v); }} options={[{ value: "active", label: "启用" }, { value: "inactive", label: "停用" }]} /><Input.Search allowClear placeholder="估值日 YYYY-MM-DD" onSearch={(v) => { setPage(1); setAsOf(v); }} style={{ width: 180 }} /></Space><Table rowKey="id" size="small" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, onChange: setPage, showSizeChanger: false }} columns={[{ title: "产品名称", dataIndex: "name", render: (v: string, r: FundListItem) => <a onClick={() => navigate(`/funds/${r.id}`)}>{v}</a> }, { title: "代码", dataIndex: "product_code", render: (v: string | null) => <span className="mono">{v ?? "—"}</span> }, { title: "状态", dataIndex: "status", render: (v: FundListItem["status"]) => <Tag color={v === "active" ? "success" : "default"}>{v === "active" ? "启用" : "停用"}</Tag> }, { title: "估值日", dataIndex: "valuation_date", render: dateStr }, { title: "单位净值", dataIndex: "unit_nav", align: "right", render: (v: string | null) => <Num>{dec(v, 4)}</Num> }, { title: "日收益", dataIndex: "daily_return", align: "right", render: (v: string | null) => <Num style={{ color: returnColor(v) }}>{pct(v)}</Num> }, { title: "质量", dataIndex: "quality_status", render: (v: FundListItem["quality_status"]) => <QualityBadge status={v} /> }]} /></Card></div>;
}
