import { useEffect, useState } from "react";
import { Alert, Button, Card, Modal, Space, Table, Tag, Upload } from "antd";
import type { UploadFile } from "antd";
import * as importsApi from "@/api/imports";
import * as downloads from "@/api/downloads";
import type { ImportBatchDetail, ImportBatchFile, ImportValidationVersion } from "@/api/types";
import { PageHeader, useToast, RoleGuard, Truncate } from "@/components";
import { IMPORT_BATCH_STATUS_LABEL, JOB_STATUS_LABEL, SOURCE_TYPE_LABEL } from "@/utils/constants";
import { timeStr } from "@/utils/format";

export default function Imports() {
  const toast = useToast(); const [rows, setRows] = useState<importsApi.ImportBatchRow[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [detail, setDetail] = useState<ImportBatchDetail | null>(null); const [validations, setValidations] = useState<ImportValidationVersion[] | null>(null); const [uploading, setUploading] = useState(false);
  async function load() { setLoading(true); setError(null); try { const result = await importsApi.listBatches({ page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("导入批次加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page]);
  useEffect(() => { if (!detail?.job || !["pending", "running", "retry_due"].includes(detail.job.status)) return; const timer = window.setInterval(() => { void importsApi.getBatch(detail.id).then((result) => { setDetail(result.data); if (!["pending", "running", "retry_due"].includes(result.data.job?.status ?? "")) { void load(); } }).catch(() => undefined); }, 3000); return () => window.clearInterval(timer); }, [detail?.id, detail?.job?.status]);
  async function upload(files: UploadFile[]) { if (!files.length || !files[0].originFileObj) return; setUploading(true); try { const batch = await importsApi.createBatch(); await importsApi.uploadFile(batch.data.id, files[0].originFileObj); const completed = await importsApi.completeBatch(batch.data.id); setDetail(completed.data); toast.success("文件已提交处理"); await load(); } catch { setError("文件上传失败，请检查文件格式后重试"); } finally { setUploading(false); } }
  async function retry(id: number) { try { await importsApi.retryBatch(id); await load(); } catch { setError("批次重试失败，请稍后重试"); } }
  async function showValidations(batchId: number) { try { const [batch, result] = await Promise.all([importsApi.getBatch(batchId), importsApi.getValidations(batchId)]); setDetail(batch.data); setValidations(result.data); } catch { setError("校验结果加载失败"); } }
  return <div className="fd-page"><PageHeader title="导入中心" desc="创建批次、上传估值表并查看后端处理状态" extra={<RoleGuard cap="imports"><Upload accept=".xls,.xlsx" multiple={false} showUploadList={false} beforeUpload={(_, fileList) => { void upload(fileList); return false; }}><Button type="primary" loading={uploading}>上传估值表</Button></Upload></RoleGuard>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Table rowKey="id" size="small" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, onChange: setPage, showSizeChanger: false }} columns={[{ title: "批次", dataIndex: "id" }, { title: "来源", dataIndex: "source_type", render: (v: keyof typeof SOURCE_TYPE_LABEL) => SOURCE_TYPE_LABEL[v] }, { title: "文件数", dataIndex: "file_count" }, { title: "状态", dataIndex: "status", render: (v: keyof typeof IMPORT_BATCH_STATUS_LABEL) => IMPORT_BATCH_STATUS_LABEL[v] }, { title: "任务状态", render: (_: unknown, r) => r.job ? JOB_STATUS_LABEL[r.job.status] : "—" }, { title: "创建时间", dataIndex: "created_at", render: timeStr }, { title: "操作", render: (_: unknown, r) => <Space><Button type="link" size="small" onClick={() => void importsApi.getBatch(r.id).then((v) => { setDetail(v.data); setValidations(null); })}>详情</Button><Button type="link" size="small" onClick={() => void showValidations(r.id)}>校验结果</Button>{r.job?.can_retry && <Button type="link" size="small" onClick={() => void retry(r.id)}>重试</Button>}</Space> }]} /></Card><Modal open={detail !== null} title={`批次详情 ${detail?.id ?? ""}`} onCancel={() => { setDetail(null); setValidations(null); }} footer={null}><Table rowKey="id" size="small" pagination={false} dataSource={detail?.files ?? []} columns={[{ title: "文件名", dataIndex: "original_filename", render: (v: string) => <Truncate value={v} maxChars={60} /> }, { title: "大小", dataIndex: "file_size", render: (v?: number) => v == null ? "—" : `${(v / 1024).toFixed(1)} KB` }, { title: "哈希", dataIndex: "file_hash", render: (v: string) => <Truncate value={v} maxChars={32} /> }, { title: "重复", dataIndex: "duplicate", render: (v: boolean) => v ? <Tag>是</Tag> : "否" }, { title: "操作", render: (_: unknown, file: ImportBatchFile) => <Button type="link" onClick={() => void downloads.downloadBlob(`/imports/${detail!.id}/source/${file.id}`, file.original_filename)}>下载原文件</Button> }]} />{validations !== null && <Table style={{ marginTop: 12 }} rowKey="version_id" size="small" pagination={false} locale={{ emptyText: "暂无校验结果" }} dataSource={validations} columns={[{ title: "估值日", dataIndex: "valuation_date" }, { title: "版本状态", dataIndex: "status" }, { title: "校验发现", dataIndex: "findings", render: (items: ImportValidationVersion["findings"]) => <Truncate value={items.map((item) => `${item.level}: ${item.message}`).join("；") || "无"} maxChars={120} /> }]} />}</Modal></div>;
}
