import { useEffect, useState } from "react";
import { Alert, Button, Card, Input, Space, Table, Tag } from "antd";
import * as mailApi from "@/api/mail";
import type { MailSettings, MailSyncResult } from "@/api/types";
import { PageHeader, RoleGuard } from "@/components";
import { useAuth } from "@/app/auth";
import { timeStr } from "@/utils/format";

export default function Mail() {
  const { session } = useAuth(); const isAdmin = session?.role === "admin";
  const [settings, setSettings] = useState<MailSettings | null>(null); const [runs, setRuns] = useState<MailSyncResult[]>([]); const [username, setUsername] = useState(""); const [code, setCode] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { const [s, r] = await Promise.all([mailApi.getSettings(), mailApi.listSyncRuns()]); setSettings(s.data); setUsername(s.data.username); setRuns(r.data); } catch { setError("邮件设置加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function saveUsername() { if (!username.trim()) return; setBusy(true); try { await mailApi.updateSettings(username); await load(); } catch { setError("邮箱账号保存失败，请检查账号格式"); } finally { setBusy(false); } }
  async function saveCode() { if (!code.trim()) return; setBusy(true); try { await mailApi.updateCredential(code); setCode(""); await load(); } catch { setError("授权码保存失败，未显示或记录授权码"); } finally { setBusy(false); } }
  async function test() { setBusy(true); try { await mailApi.testConnection(); await load(); } catch { setError("邮件连接测试失败，请检查服务器配置和授权码"); } finally { setBusy(false); } }
  async function sync() { setBusy(true); try { await mailApi.syncNow(); await load(); } catch { setError("邮件同步失败，请查看同步记录"); } finally { setBusy(false); } }
  async function toggle() { setBusy(true); try { if (settings?.auto_sync_enabled) await mailApi.pause(); else await mailApi.resume(); await load(); } catch { setError("自动同步状态更新失败"); } finally { setBusy(false); } }
  return <div className="fd-page"><PageHeader title="邮件接入" desc="管理专用邮箱账号、授权码、连接测试和附件同步" />{error && <Alert type="error" showIcon message={error} />}<Card loading={loading} title="邮箱设置" extra={<Tag color={settings?.configured ? "success" : "default"}>{settings?.configured ? "已配置" : "未配置"}</Tag>}><Space direction="vertical" style={{ width: "100%" }}><div>服务器：{settings?.host || "未配置"}:{settings?.port ?? "—"}</div><Space wrap><Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="输入邮箱账号" autoComplete="username" disabled={!isAdmin} style={{ width: 260 }} /><RoleGuard cap="mail">{isAdmin && <Button type="primary" loading={busy} onClick={() => void saveUsername()}>保存账号</Button>}</RoleGuard></Space><div>当前账号：{settings?.username || "未配置"}　自动同步：{settings?.auto_sync_enabled ? "运行中" : "已暂停"}</div><RoleGuard cap="mail"><Space wrap>{isAdmin && <><Input.Password value={code} onChange={(e) => setCode(e.target.value)} placeholder="输入邮箱授权码" autoComplete="new-password" /><Button type="primary" loading={busy} onClick={() => void saveCode()}>保存授权码</Button><Button loading={busy} onClick={() => void test()}>测试连接</Button></>}<Button loading={busy} onClick={() => void sync()}>立即同步</Button>{isAdmin && <Button loading={busy} onClick={() => void toggle()}>{settings?.auto_sync_enabled ? "暂停同步" : "恢复同步"}</Button>}</Space></RoleGuard></Space></Card><Card style={{ marginTop: 12 }} title="同步记录"><Table rowKey="run_id" size="small" loading={loading} dataSource={runs} pagination={{ pageSize: 10, showSizeChanger: false }} columns={[{ title: "运行编号", dataIndex: "run_id" }, { title: "状态", dataIndex: "status" }, { title: "创建时间", dataIndex: "created_at", render: timeStr }, { title: "发现邮件", dataIndex: "messages_seen" }, { title: "导入附件", dataIndex: "attachments_imported" }, { title: "失败附件", dataIndex: "failed_attachments" }, { title: "错误数", dataIndex: "error_count" }]} /></Card></div>;
}
