import { useEffect, useState } from "react";
import { Alert, Button, Card, Input, Space, Table, Tag, Divider } from "antd";
import * as mailApi from "@/api/mail";
import { apiErrorMessage } from "@/api/client";
import type { MailSettings, MailSyncResult } from "@/api/types";
import { PageHeader, useToast } from "@/components";
import { useAuth } from "@/app/auth";
import { timeStr } from "@/utils/format";

export default function Mail() {
  const { session } = useAuth(); const isAdmin = session?.role === "admin";
  const toast = useToast();
  const [settings, setSettings] = useState<MailSettings | null>(null); const [runs, setRuns] = useState<MailSyncResult[]>([]); const [username, setUsername] = useState(""); const [code, setCode] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [activeAction, setActiveAction] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { const [s, r] = await Promise.all([mailApi.getSettings(), mailApi.listSyncRuns()]); setSettings(s.data); setUsername(s.data.username); setRuns(r.data); } catch { setError("邮件设置加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function saveUsername() { if (!username.trim()) return; setBusy(true); try { await mailApi.updateSettings(username); await load(); } catch { setError("邮箱账号保存失败，请检查账号格式"); } finally { setBusy(false); } }
  async function saveCode() { if (!code.trim()) return; setBusy(true); try { await mailApi.updateCredential(code); setCode(""); await load(); } catch { setError("授权码保存失败，未显示或记录授权码"); } finally { setBusy(false); } }
  async function test() { setError(null); setBusy(true); setActiveAction("连接测试"); try { await mailApi.testConnection(); toast.success("邮箱连接测试成功"); await load(); } catch (cause) { const detail = apiErrorMessage(cause, ""); const messages: Record<string, string> = { mail_not_configured: "邮箱服务器、账号或授权码未配置", mail_credential_unavailable: "授权码文件不可读，请检查文件权限和挂载", mail_connection_timeout: "连接邮箱服务器超时，请检查容器外网出口", mail_dns_failed: "无法解析邮箱服务器地址，请检查 DNS（域名解析）", mail_tls_failed: "邮箱服务器安全连接失败，请检查 SSL（安全连接）设置", mail_connection_failed: "邮箱服务器连接失败，请检查网络和服务器配置" }; setError(messages[detail] ?? "邮件连接测试失败，请检查服务器配置和网络"); } finally { setBusy(false); setActiveAction(null); } }
  async function sync() { setError(null); setBusy(true); setActiveAction("同步"); try { const result = await mailApi.syncNow(); const summary = result.data; toast.success(`邮件同步完成：发现 ${summary.messages_seen ?? 0} 封邮件，导入 ${summary.attachments_imported ?? 0} 个附件`); await load(); } catch (cause) { setError(cause instanceof DOMException && cause.name === "AbortError" ? "邮件同步超过 2 分钟仍未返回，请查看同步记录和服务日志" : "邮件同步失败，请查看同步记录"); } finally { setBusy(false); setActiveAction(null); } }
  async function toggle() { setBusy(true); try { if (settings?.auto_sync_enabled) await mailApi.pause(); else await mailApi.resume(); await load(); } catch { setError("自动同步状态更新失败"); } finally { setBusy(false); } }
  return <div className="fd-page"><PageHeader title="邮件接入" desc="管理专用邮箱账号、授权码、连接测试和附件同步" />{error && <Alert type="error" showIcon closable onClose={() => setError(null)} message={error} />}<Card loading={loading} title="邮箱设置" extra={<Tag color={settings?.configured ? "success" : "default"}>{settings?.configured ? "已配置" : "未配置"}</Tag>}><Space direction="vertical" size={16} style={{ width: "100%" }}><div className="fd-mail-meta"><span>服务器</span><strong>{settings?.host || "未配置"}:{settings?.port ?? "—"}</strong><span>当前账号</span><strong>{settings?.username || "未配置"}</strong><span>自动同步</span><Tag color={settings?.auto_sync_enabled ? "green" : "default"}>{settings?.auto_sync_enabled ? "运行中" : "已暂停"}</Tag></div><Divider style={{ margin: 0 }} /><section><div className="fd-section-title">账号配置</div><Space wrap style={{ marginTop: 10 }}><Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="输入邮箱账号" autoComplete="username" disabled={!isAdmin} style={{ width: 280 }} />{isAdmin && <Button type="primary" loading={busy} onClick={() => void saveUsername()}>保存账号</Button>}</Space></section><section><div className="fd-section-title">授权码与连接</div><Space wrap style={{ marginTop: 10 }}>{isAdmin && <><Input.Password value={code} onChange={(e) => setCode(e.target.value)} placeholder="输入邮箱授权码" autoComplete="new-password" style={{ width: 280 }} /><Button type="primary" loading={busy} onClick={() => void saveCode()}>保存授权码</Button><Button loading={busy && activeAction === "连接测试"} disabled={busy} onClick={() => void test()}>测试连接</Button></>}</Space></section><section><div className="fd-section-title">同步控制</div><Space wrap style={{ marginTop: 10 }}><Button type="primary" loading={busy && activeAction === "同步"} disabled={busy} onClick={() => void sync()}>立即同步</Button>{isAdmin && <Button loading={busy && activeAction === "切换"} disabled={busy} onClick={() => void toggle()}>{settings?.auto_sync_enabled ? "暂停同步" : "恢复同步"}</Button>}<span className="fd-caption">{activeAction ? `${activeAction}进行中，请稍候…` : "同步将读取收件箱并处理可识别的表格附件"}</span></Space></section></Space></Card><Card style={{ marginTop: 12 }} title="同步记录"><Table rowKey="run_id" size="small" loading={loading} dataSource={runs} pagination={{ pageSize: 10, showSizeChanger: false }} columns={[{ title: "运行编号", dataIndex: "run_id" }, { title: "状态", dataIndex: "status" }, { title: "创建时间", dataIndex: "created_at", render: timeStr }, { title: "发现邮件", dataIndex: "messages_seen" }, { title: "导入附件", dataIndex: "attachments_imported" }, { title: "失败附件", dataIndex: "failed_attachments" }, { title: "错误数", dataIndex: "error_count" }]} /></Card></div>;
}
