import { useEffect, useState } from "react";
import { Alert, Button, Descriptions, Divider, Drawer, Empty, Input, Modal, Pagination, Space, Table, Tag, Typography } from "antd";
import * as reviewsApi from "@/api/reviews";
import * as downloads from "@/api/downloads";
import type { ImportValidationFinding, ReviewItem } from "@/api/types";
import { LevelTag, PageHeader, Truncate, useConfirm, useToast } from "@/components";
import { VALUATION_STATUS_LABEL, type ValidationLevel } from "@/utils/constants";
import { dateStr } from "@/utils/format";

const activeFindings = (row: ReviewItem) => (row.findings ?? []).filter((finding) => !finding.ignored);
function formatBytes(value: number | null) { if (value == null) return "—"; if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB`; }

function FindingTable({ findings }: { findings: ImportValidationFinding[] }) {
  if (!findings.length) return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="这条版本没有可展示的校验异常" />;
  return <Table rowKey={(finding, index) => `${finding.rule_code}-${index}`} size="small" pagination={false} dataSource={findings} columns={[
    { title: "等级", dataIndex: "level", width: 82, render: (value: ValidationLevel, finding: ImportValidationFinding) => <Space direction="vertical" size={2}><LevelTag level={value} />{finding.ignored && <Tag>已忽略</Tag>}</Space> },
    { title: "规则", dataIndex: "rule_code", width: 170, render: (value: string) => <Typography.Text code>{value}</Typography.Text> },
    { title: "异常说明", dataIndex: "message", render: (value: string) => <Typography.Text>{value || "未提供说明"}</Typography.Text> },
    { title: "数值对比", width: 210, render: (_: unknown, finding: ImportValidationFinding) => <div className="fd-caption">实际：{finding.actual_value ?? "—"}<br />期望：{finding.expected_value ?? "—"}<br />差异：{finding.difference ?? "—"}</div> },
    { title: "来源位置", dataIndex: "source_location", width: 180, render: (value: string | null) => <Truncate value={value ?? "未记录"} maxChars={64} /> },
    { title: "处理记录", width: 180, render: (_: unknown, finding: ImportValidationFinding) => finding.ignored ? <Typography.Text type="secondary">{finding.ignored_reason || "人工发布时忽略"}</Typography.Text> : <Typography.Text type="secondary">待人工处理</Typography.Text> },
  ]} />;
}

export default function Reviews() {
  const toast = useToast(); const confirm = useConfirm(); const [rows, setRows] = useState<ReviewItem[]>([]); const [selected, setSelected] = useState<ReviewItem | null>(null); const [note, setNote] = useState(""); const [status, setStatus] = useState<ReviewItem["status"]>("pending_review"); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [ackOpen, setAckOpen] = useState(false);
  async function load() { setLoading(true); setError(null); try { const result = await reviewsApi.listReviews({ status, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("复核队列加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page, status]);
  async function acknowledge() { if (!selected || !note.trim()) return; try { const result = await reviewsApi.acknowledgeReview(selected.id, { allow_publish: true, note: note.trim() }); if (result.data.status === "publishable") await reviewsApi.publishVersion(selected.id, { reason: note.trim(), confirm_warnings: true }); toast.success("版本已发布，异常已记为人工忽略"); setAckOpen(false); setSelected(null); setNote(""); await load(); } catch { setError("复核或发布失败，请检查版本状态后重试"); } }
  async function publish(row: ReviewItem) { const count = activeFindings(row).length; const reason = await confirm({ title: "发布并忽略校验异常", description: `确认发布后，${count} 条当前异常会标记为“人工已忽略”，后续质量看板不再重复提醒；原始异常和操作原因仍保留在审计记录中。`, reasonLabel: "忽略原因", reasonRequired: true, okText: "确认发布" }); if (reason === null) return; try { await reviewsApi.publishVersion(row.id, { reason, confirm_warnings: true }); toast.success(`版本已发布，${count} 条异常已忽略`); setSelected(null); await load(); } catch { setError("版本发布失败，请检查当前状态后重试"); } }
  async function action(kind: "reject" | "revoke" | "restore", row: ReviewItem) { const reason = await confirm({ title: kind === "reject" ? "驳回版本" : kind === "revoke" ? "撤回版本" : "恢复版本", description: "操作原因将写入审计日志。", reasonRequired: true, danger: kind !== "restore", okText: "确认" }); if (reason === null) return; try { if (kind === "reject") await reviewsApi.rejectVersion(row.id, reason); else if (kind === "revoke") await reviewsApi.revokeVersion(row.id, reason); else await reviewsApi.restoreVersion(row.id, reason); toast.success("版本状态已更新"); setSelected(null); await load(); } catch { setError("版本操作失败，请检查当前状态和权限"); } }
  const selectedFindings = selected?.findings ?? [];
  return <div className="fd-page"><PageHeader title="异常复核" desc="先看清异常与原始来源，再决定发布、驳回或撤回" extra={<Space wrap>{(["pending_review", "publishable", "published", "revoked"] as const).map((value) => <Button key={value} type={status === value ? "primary" : "default"} onClick={() => { setPage(1); setStatus(value); }}>{VALUATION_STATUS_LABEL[value]}</Button>)}<Button onClick={() => void load()} loading={loading}>刷新</Button></Space>} />{error && <Alert type="error" showIcon message={error} />}<Table style={{ marginTop: 12 }} rowKey="id" size="small" loading={loading} dataSource={rows} pagination={false} columns={[{ title: "产品", dataIndex: "fund_name" }, { title: "估值日", dataIndex: "valuation_date", render: dateStr }, { title: "版本", dataIndex: "version_no", render: (value: number) => `v${value}` }, { title: "待处理异常", render: (_: unknown, row: ReviewItem) => <Tag color={row.critical_count ? "error" : row.warning_count ? "warning" : "default"}>{row.critical_count + row.warning_count} 条</Tag> }, { title: "已忽略", dataIndex: "ignored_count", render: (value: number) => value || "—" }, { title: "原始文件", dataIndex: "source_filename", render: (value: string | null) => <Truncate value={value ?? "未关联文件"} maxChars={32} /> }, { title: "操作", render: (_: unknown, row: ReviewItem) => <Space><Button size="small" onClick={() => setSelected(row)}>查看详情</Button>{row.status === "publishable" && <Button size="small" type="primary" onClick={() => void publish(row)}>发布并忽略</Button>}{row.status === "pending_review" && <><Button size="small" type="primary" onClick={() => { setSelected(row); setAckOpen(true); }}>复核并发布</Button><Button size="small" danger onClick={() => void action("reject", row)}>驳回</Button></>}{row.status === "published" && <Button size="small" danger onClick={() => void action("revoke", row)}>撤回</Button>}{(row.status === "revoked" || row.status === "superseded") && <Button size="small" onClick={() => void action("restore", row)}>恢复</Button>}</Space> }]} /><Pagination style={{ marginTop: 12, textAlign: "right" }} current={page} pageSize={20} total={total} showSizeChanger={false} onChange={setPage} />
  <Modal open={selected !== null && ackOpen} title="复核并发布" onCancel={() => setAckOpen(false)} onOk={() => void acknowledge()} okText="确认发布并忽略" okButtonProps={{ disabled: !note.trim() }}><Alert type="warning" showIcon message={`发布后将把 ${selected ? activeFindings(selected).length : 0} 条异常标记为人工忽略`} description="这不会删除原始记录；质量看板和复核队列将不再重复提示。" /><Input.TextArea style={{ marginTop: 16 }} value={note} onChange={(event) => setNote(event.target.value)} placeholder="填写你接受该异常的原因，例如：已与业务员核对原始估值表" maxLength={2000} showCount rows={4} /></Modal>
  <Drawer open={selected !== null && !ackOpen} width={Math.min(820, window.innerWidth - 24)} title={selected ? `复核详情 · ${selected.fund_name}` : "复核详情"} onClose={() => setSelected(null)} destroyOnClose>{selected && <><Descriptions bordered size="small" column={2}><Descriptions.Item label="产品">{selected.fund_name}</Descriptions.Item><Descriptions.Item label="估值日">{dateStr(selected.valuation_date)}</Descriptions.Item><Descriptions.Item label="版本">v{selected.version_no}</Descriptions.Item><Descriptions.Item label="状态">{VALUATION_STATUS_LABEL[selected.status]}</Descriptions.Item><Descriptions.Item label="待处理异常">{activeFindings(selected).length} 条</Descriptions.Item><Descriptions.Item label="已忽略异常">{selected.ignored_count || 0} 条</Descriptions.Item></Descriptions><Divider orientation="left">原始文件</Divider>{selected.source_filename ? <Space direction="vertical" size={4} style={{ width: "100%" }}><Typography.Text strong>{selected.source_filename}</Typography.Text><Typography.Text type="secondary">批次 #{selected.import_batch_id ?? "—"} · {formatBytes(selected.source_file_size)} · 文件指纹 {selected.source_file_hash?.slice(0, 16) ?? "—"}…</Typography.Text>{selected.source_file_id && selected.import_batch_id && <Button type="link" style={{ padding: 0, alignSelf: "flex-start" }} onClick={() => void downloads.downloadBlob(`/imports/${selected.import_batch_id}/source/${selected.source_file_id}`, selected.source_filename!)}>下载原始文件</Button>}</Space> : <Typography.Text type="secondary">该版本没有关联可下载的原始文件。</Typography.Text>}<Divider orientation="left">逐条校验结果</Divider><FindingTable findings={selectedFindings} />{selected.status === "publishable" && activeFindings(selected).length > 0 && <Button type="primary" style={{ marginTop: 16 }} onClick={() => void publish(selected)}>发布并忽略这些异常</Button>}</>}</Drawer></div>;
}
