import { useEffect, useState } from "react";
import { Alert, Button, Card, Empty, Input, Modal, Pagination, Space, Table, Tag } from "antd";
import * as reviewsApi from "@/api/reviews";
import type { ReviewItem } from "@/api/types";
import { PageHeader, useConfirm, useToast } from "@/components";
import { dateStr } from "@/utils/format";

export default function Reviews() {
  const toast = useToast(); const confirm = useConfirm(); const [rows, setRows] = useState<ReviewItem[]>([]); const [selected, setSelected] = useState<ReviewItem | null>(null); const [note, setNote] = useState(""); const [status, setStatus] = useState<ReviewItem["status"]>("pending_review"); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [ackOpen, setAckOpen] = useState(false);
  async function load() { setLoading(true); setError(null); try { const result = await reviewsApi.listReviews({ status, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("复核队列加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page, status]);
  async function acknowledge() { if (!selected || !note.trim()) return; try { const result = await reviewsApi.acknowledgeReview(selected.id, { allow_publish: true, note: note.trim() }); if (result.data.status === "publishable") await reviewsApi.publishVersion(selected.id); toast.success("复核处理已完成"); setAckOpen(false); setSelected(null); setNote(""); await load(); } catch { setError("复核或发布失败，请检查版本状态后重试"); } }
  async function action(kind: "reject" | "revoke" | "restore", row: ReviewItem) { const reason = await confirm({ title: kind === "reject" ? "驳回版本" : kind === "revoke" ? "撤回版本" : "恢复版本", description: "操作原因将写入审计日志。", reasonRequired: true, danger: kind !== "restore", okText: "确认" }); if (reason === null) return; try { if (kind === "reject") await reviewsApi.rejectVersion(row.id, reason); else if (kind === "revoke") await reviewsApi.revokeVersion(row.id, reason); else await reviewsApi.restoreVersion(row.id, reason); toast.success("版本状态已更新"); setSelected(null); await load(); } catch { setError("版本操作失败，请检查当前状态和权限"); } }
  return <div className="fd-page"><PageHeader title="异常复核" desc="查看估值版本并执行确认、发布、驳回、撤回或恢复" extra={<Space><Button type={status === "pending_review" ? "primary" : "default"} onClick={() => { setPage(1); setStatus("pending_review"); }}>待复核</Button><Button onClick={() => { setPage(1); setStatus("published"); }}>已发布</Button><Button onClick={() => { setPage(1); setStatus("revoked"); }}>已撤回</Button><Button onClick={() => void load()} loading={loading}>刷新</Button></Space>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Table rowKey="id" size="small" loading={loading} dataSource={rows} pagination={false} columns={[{ title: "产品", dataIndex: "fund_name" }, { title: "估值日", dataIndex: "valuation_date", render: dateStr }, { title: "版本", dataIndex: "version_no", render: (v: number) => `v${v}` }, { title: "阻断级", dataIndex: "critical_count" }, { title: "警告级", dataIndex: "warning_count" }, { title: "操作", render: (_: unknown, row: ReviewItem) => <Space><Button size="small" onClick={() => setSelected(row)}>查看</Button>{row.status === "pending_review" && <><Button size="small" type="primary" onClick={() => { setSelected(row); setAckOpen(true); }}>确认并发布</Button><Button size="small" danger onClick={() => void action("reject", row)}>驳回</Button></>}{row.status === "published" && <Button size="small" danger onClick={() => void action("revoke", row)}>撤回</Button>}{(row.status === "revoked" || row.status === "superseded") && <Button size="small" onClick={() => void action("restore", row)}>恢复</Button>}</Space> }]} /><Pagination style={{ marginTop: 12, textAlign: "right" }} current={page} pageSize={20} total={total} showSizeChanger={false} onChange={setPage} /></Card><Modal open={selected !== null && ackOpen} title="确认复核并发布" onCancel={() => setAckOpen(false)} onOk={() => void acknowledge()} okText="确认并发布"><Input.TextArea value={note} onChange={(e) => setNote(e.target.value)} placeholder="填写复核意见" maxLength={2000} showCount rows={4} /></Modal>{selected && !ackOpen && <Modal open title={`复核摘要：${selected.fund_name}`} onCancel={() => setSelected(null)} footer={<Button onClick={() => setSelected(null)}>关闭</Button>}><p>估值日：{dateStr(selected.valuation_date)}</p><p>版本：v{selected.version_no}　状态：<Tag>{selected.status}</Tag></p><p>阻断级发现：{selected.critical_count}　警告级发现：{selected.warning_count}</p><Empty description="详细校验结果请在导入批次详情中查看" /></Modal>}</div>;
}
