import { useEffect, useState } from "react";
import { Alert, Button, Card, Form, Input, Modal, Select, Space, Table, Tag } from "antd";
import { useSearchParams } from "react-router-dom";
import * as riskApi from "@/api/risk";
import type { RiskEvent } from "@/api/types";
import { PageHeader, RoleGuard } from "@/components";
import { dateStr, timeStr } from "@/utils/format";
import { RISK_EVENT_STATUS_LABEL, RISK_SEVERITY_LABEL, type RiskEventStatus, type RiskSeverity } from "@/utils/constants";

export default function RiskOverview() {
  const [params] = useSearchParams(); const fundParam = params.get("fund"); const urlFundId = fundParam && Number.isInteger(Number(fundParam)) ? Number(fundParam) : undefined; const [rows, setRows] = useState<RiskEvent[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [filters, setFilters] = useState<riskApi.RiskEventParams>({ fund_id: urlFundId }); const [event, setEvent] = useState<RiskEvent | null>(null); const [form] = Form.useForm();
  async function load() { setLoading(true); setError(null); try { const result = await riskApi.listEvents({ ...filters, page, page_size: 20 }); setRows(result.data); setTotal(result.meta.total); } catch { setError("风险事件加载失败，请刷新重试"); } finally { setLoading(false); } }
  useEffect(() => { setPage(1); setFilters((current) => ({ ...current, fund_id: urlFundId })); }, [fundParam]);
  useEffect(() => { void load(); }, [page, filters]);
  async function submit() { const values = await form.validateFields(); try { await riskApi.handleEvent(event!.id, values); setEvent(null); form.resetFields(); await load(); } catch { setError("风险事件处理失败，请检查权限和输入后重试"); } }
  const color = (value: RiskSeverity | RiskEventStatus) => value === "critical" || value === "open" ? "error" : value === "warning" || value === "acknowledged" ? "warning" : value === "resolved" ? "success" : "default";
  return <div className="fd-page"><PageHeader title="风险概览" desc="查看后端生成的风险事件并记录处理结果" extra={<Button onClick={() => void load()} loading={loading}>刷新</Button>} />{error && <Alert type="error" showIcon message={error} />}<Card style={{ marginTop: 12 }}><Space wrap className="fd-filterbar"><Select allowClear placeholder="严重度" value={filters.severity} onChange={(v) => { setPage(1); setFilters((f) => ({ ...f, severity: v })); }} options={Object.entries(RISK_SEVERITY_LABEL).map(([value, label]) => ({ value, label }))} /><Select allowClear placeholder="处理状态" value={filters.status} onChange={(v) => { setPage(1); setFilters((f) => ({ ...f, status: v })); }} options={Object.entries(RISK_EVENT_STATUS_LABEL).map(([value, label]) => ({ value, label }))} /><Button onClick={() => { setPage(1); setFilters({ fund_id: urlFundId }); }}>重置筛选</Button></Space><Table rowKey="id" size="small" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, onChange: setPage, showSizeChanger: false }} columns={[{ title: "产品", dataIndex: "fund_name" }, { title: "估值日", dataIndex: "valuation_date", render: dateStr }, { title: "规则", dataIndex: "rule_code" }, { title: "严重度", dataIndex: "severity", render: (v: RiskSeverity) => <Tag color={color(v)}>{RISK_SEVERITY_LABEL[v]}</Tag> }, { title: "状态", dataIndex: "status", render: (v: RiskEventStatus) => <Tag color={color(v)}>{RISK_EVENT_STATUS_LABEL[v]}</Tag> }, { title: "首次触发", dataIndex: "first_triggered_at", render: timeStr }, { title: "处理意见", dataIndex: "handling_note", render: (v: string | null) => v ?? "—" }, { title: "操作", render: (_: unknown, r: RiskEvent) => <RoleGuard cap="write"><Button size="small" disabled={r.status !== "open" && r.status !== "acknowledged"} onClick={() => setEvent(r)}>处理</Button></RoleGuard> }]} /></Card><Modal open={event !== null} title="处理风险事件" onCancel={() => setEvent(null)} onOk={() => void submit()} okText="提交处理" destroyOnClose><Form form={form} layout="vertical"><Form.Item name="status" label="处理结果" rules={[{ required: true }]}><Select options={["acknowledged", "resolved", "ignored"].map((value) => ({ value, label: RISK_EVENT_STATUS_LABEL[value as RiskEventStatus] }))} /></Form.Item><Form.Item name="handling_note" label="处理意见" rules={[{ required: true }]}><Input.TextArea rows={4} maxLength={4000} showCount /></Form.Item><Form.Item name="evidence_reference" label="证据引用"><Input maxLength={1000} /></Form.Item></Form></Modal></div>;
}
